-- Version del servidor: 8.0.17
-- Version de PHP: 7.3.10
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "Europe/Madrid";

-- --
-- Base de datos: `uca101`
-- --

-- CREATE DATABASE IF NOT EXISTS `uca101`
CREATE DATABASE IF NOT EXISTS `uca101`
DEFAULT CHARACTER SET utf8mb4
COLLATE utf8mb4_0900_ai_ci;
USE `uca101`;

CREATE TABLE `Usuario` (
	`id` INT AUTO_INCREMENT PRIMARY KEY NOT NULL, 
	`user_name` VARCHAR(20) NOT NULL,
	`password` VARCHAR(10) NOT NULL,
	`email` VARCHAR(20) NOT NULL,
	`nombre` VARCHAR(20) NOT NULL,
	`apellidos` VARCHAR(64) NOT NULL,
	`rol` set('estudiante','profesor','administrador') 
	CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'estudiante'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `Grado` (
	`id` INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	`codigo` VARCHAR(20) NOT NULL,
	`nombre` VARCHAR(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `Asignatura` (
	`id` INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	`id_Grado` INT NOT NULL, 
	FOREIGN KEY(`id_Grado`) REFERENCES Grado(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
	`codigo` VARCHAR(20) NOT NULL,
	`nombre` VARCHAR(20) NOT NULL,
	`fechaCurso` INT(4) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `UsuarioAsignatura` (
	`id` INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	`id_Usuario` INT NOT NULL, 
	FOREIGN KEY(`id_Usuario`) REFERENCES Usuario(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
	`id_Asignatura` INT NOT NULL, 
	FOREIGN KEY(`id_Asignatura`) REFERENCES Asignatura(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `Tema` (
	`id` INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	`id_Asignatura` INT NOT NULL, 
	FOREIGN KEY(`id_Asignatura`) REFERENCES Asignatura(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
	`nombre` VARCHAR(20) NOT NULL,
	`numero` INT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `Pregunta` (
	`id` INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	`id_Tema` INT NOT NULL, 
	FOREIGN KEY(`id_Tema`) REFERENCES Tema(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `Respuesta` (
	`id` INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	`id_Pregunta` INT NOT NULL, 
	FOREIGN KEY(`id_Pregunta`) REFERENCES Pregunta(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `Informe` (
	`id` INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	`nota_media` FLOAT,
	`numero_suspensos` INT,
	`numero_aprobados` INT,
	`numero_notables` INT,
	`numero_sobresalientes` INT

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `Examen` (
	`id` INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	`id_Usuario` INT NOT NULL, 
	FOREIGN KEY(`id_Usuario`) REFERENCES Usuario(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
	`id_Informe` INT NOT NULL, 
	FOREIGN KEY(`id_Informe`) REFERENCES Informe(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
	`nota` INT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `ExamenPregunta` (
	`id` INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	`id_Examen` INT NOT NULL, 
	FOREIGN KEY(`id_Examen`) REFERENCES Examen(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
	`id_Pregunta` INT NOT NULL, 
	FOREIGN KEY(`id_Pregunta`) REFERENCES Pregunta(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `TemaPregunta` (
	`id` INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	`id_Tema` INT NOT NULL, 
	FOREIGN KEY(`id_Tema`) REFERENCES Tema(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
	`id_Pregunta` INT NOT NULL, 
	FOREIGN KEY(`id_Pregunta`) REFERENCES Pregunta(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;